export const DUMMY_DATA = [
    {
        id: 1,
        name: "John Doe",
        email: "john.doe@hashmicro.com",
        department: "Engineering",
        position: "Senior Developer",
        status: true,
        notes: "Team lead for frontend projects",
    },
    {
        id: 2,
        name: "Jane Smith",
        email: "jane.smith@hashmicro.com",
        department: "Marketing",
        position: "Marketing Manager",
        status: true,
        notes: "Handles digital marketing campaigns",
    },
    {
        id: 3,
        name: "Robert Johnson",
        email: "robert.j@hashmicro.com",
        department: "Sales",
        position: "Sales Representative",
        status: false,
        notes: "On leave until March",
    },
    {
        id: 4,
        name: "Emily Davis",
        email: "emily.davis@hashmicro.com",
        department: "Human Resources",
        position: "HR Specialist",
        status: true,
        notes: "Recruitment and onboarding specialist",
    },
    {
        id: 5,
        name: "Michael Wilson",
        email: "michael.w@hashmicro.com",
        department: "Finance",
        position: "Financial Analyst",
        status: true,
        notes: "Quarterly reporting lead",
    },
    {
        id: 6,
        name: "Sarah Brown",
        email: "sarah.b@hashmicro.com",
        department: "Engineering",
        position: "Backend Developer",
        status: true,
        notes: "API development specialist",
    },
    {
        id: 7,
        name: "David Lee",
        email: "david.lee@hashmicro.com",
        department: "Operations",
        position: "Operations Manager",
        status: true,
        notes: "Process optimization lead",
    },
    {
        id: 8,
        name: "Lisa Anderson",
        email: "lisa.a@hashmicro.com",
        department: "Marketing",
        position: "Content Specialist",
        status: false,
        notes: "Content creation and social media",
    },
    {
        id: 9,
        name: "Kevin Martinez",
        email: "kevin.m@hashmicro.com",
        department: "Engineering",
        position: "DevOps Engineer",
        status: true,
        notes: "CI/CD and infrastructure",
    },
    {
        id: 10,
        name: "Amanda Taylor",
        email: "amanda.t@hashmicro.com",
        department: "Sales",
        position: "Account Executive",
        status: true,
        notes: "Enterprise accounts manager",
    },
    {
        id: 11,
        name: "Christopher White",
        email: "chris.w@hashmicro.com",
        department: "Engineering",
        position: "QA Engineer",
        status: true,
        notes: "Quality assurance lead",
    },
    {
        id: 12,
        name: "Jennifer Garcia",
        email: "jennifer.g@hashmicro.com",
        department: "Human Resources",
        position: "HR Manager",
        status: true,
        notes: "Employee relations and benefits",
    },
    {
        id: 13,
        name: "Daniel Harris",
        email: "daniel.h@hashmicro.com",
        department: "Finance",
        position: "Accountant",
        status: true,
        notes: "Accounts payable and receivable",
    },
    {
        id: 14,
        name: "Michelle Clark",
        email: "michelle.c@hashmicro.com",
        department: "Marketing",
        position: "SEO Specialist",
        status: true,
        notes: "Search engine optimization",
    },
    {
        id: 15,
        name: "Ryan Lewis",
        email: "ryan.l@hashmicro.com",
        department: "Engineering",
        position: "Frontend Developer",
        status: true,
        notes: "React and Vue specialist",
    },
    {
        id: 16,
        name: "Stephanie Walker",
        email: "stephanie.w@hashmicro.com",
        department: "Sales",
        position: "Sales Manager",
        status: true,
        notes: "Sales team lead",
    },
    {
        id: 17,
        name: "Brandon Hall",
        email: "brandon.h@hashmicro.com",
        department: "Operations",
        position: "Logistics Coordinator",
        status: false,
        notes: "On temporary assignment",
    },
    {
        id: 18,
        name: "Nicole Young",
        email: "nicole.y@hashmicro.com",
        department: "Engineering",
        position: "Data Engineer",
        status: true,
        notes: "Data pipeline development",
    },
    {
        id: 19,
        name: "Justin Allen",
        email: "justin.a@hashmicro.com",
        department: "Marketing",
        position: "Brand Manager",
        status: true,
        notes: "Brand strategy and identity",
    },
    {
        id: 20,
        name: "Rebecca King",
        email: "rebecca.k@hashmicro.com",
        department: "Finance",
        position: "Budget Analyst",
        status: true,
        notes: "Budget planning and analysis",
    },
    {
        id: 21,
        name: "Andrew Scott",
        email: "andrew.s@hashmicro.com",
        department: "Engineering",
        position: "Mobile Developer",
        status: true,
        notes: "iOS and Android development",
    },
    {
        id: 22,
        name: "Samantha Green",
        email: "samantha.g@hashmicro.com",
        department: "Human Resources",
        position: "Training Coordinator",
        status: true,
        notes: "Employee training programs",
    },
    {
        id: 23,
        name: "Tyler Adams",
        email: "tyler.a@hashmicro.com",
        department: "Sales",
        position: "Business Development",
        status: true,
        notes: "New market expansion",
    },
    {
        id: 24,
        name: "Megan Baker",
        email: "megan.b@hashmicro.com",
        department: "Engineering",
        position: "Security Engineer",
        status: true,
        notes: "Application security",
    },
    {
        id: 25,
        name: "Eric Nelson",
        email: "eric.n@hashmicro.com",
        department: "Operations",
        position: "Facilities Manager",
        status: true,
        notes: "Office management",
    },
    {
        id: 26,
        name: "Rachel Carter",
        email: "rachel.c@hashmicro.com",
        department: "Marketing",
        position: "Social Media Manager",
        status: true,
        notes: "Social media strategy",
    },
    {
        id: 27,
        name: "Jason Mitchell",
        email: "jason.m@hashmicro.com",
        department: "Engineering",
        position: "Tech Lead",
        status: true,
        notes: "Architecture and mentorship",
    },
    {
        id: 28,
        name: "Lauren Perez",
        email: "lauren.p@hashmicro.com",
        department: "Finance",
        position: "Payroll Specialist",
        status: true,
        notes: "Payroll processing",
    },
    {
        id: 29,
        name: "Brian Roberts",
        email: "brian.r@hashmicro.com",
        department: "Sales",
        position: "Territory Manager",
        status: false,
        notes: "Regional sales - West",
    },
    {
        id: 30,
        name: "Christina Turner",
        email: "christina.t@hashmicro.com",
        department: "Human Resources",
        position: "Recruiter",
        status: true,
        notes: "Technical recruitment",
    },
    {
        id: 31,
        name: "Matthew Phillips",
        email: "matthew.p@hashmicro.com",
        department: "Engineering",
        position: "Cloud Architect",
        status: true,
        notes: "AWS and GCP infrastructure",
    },
    {
        id: 32,
        name: "Ashley Campbell",
        email: "ashley.c@hashmicro.com",
        department: "Marketing",
        position: "Email Marketing Specialist",
        status: true,
        notes: "Campaign automation",
    },
];
